# Generated by Django 3.1.4 on 2021-01-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210126_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
