# Generated by Django 3.1.4 on 2021-01-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210127_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_favorites',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
