# Generated by Django 3.1.4 on 2021-02-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210128_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
